lib/commands/setup.js
- change from 'wp8' to 'windows' section for setup.
- save publisherGuid as windows.phone.publisherGuid
=> Fix TIMOB-18344 CLI: the windows subcommand of ti setup should manage the windows.phone.publisherGuid value

lib/commands/setup.js
https://jira.appcelerator.org/browse/TIMOB-17636
=> [TIMOB-17636] Create Titanium SDK folder if it doesn't exist

hooks/tisdk3fixes.js, lib/commands/info.js, lib/commands/sdk.js
https://jira.appcelerator.org/browse/TIMOB-18351
=> [TIMOB-18351] Deprecate iOS and Android modules in node-appc

lib/commands/lib/proxy_detect.js, lib/commands/setup.js
https://jira.appcelerator.org/browse/TIMOB-18162
=> [TIMOB-18162] Autodetect proxy configuration within ti setup

lib/context.js
https://jira.appcelerator.org/browse/TIMOB-17605
platform value is lost after mix.
=> [TIMOB-17605] : CLI throws an error while reading platform input value given for “ti build -p” or “ti build —platform”

CHANGELOG.md, lib/titanium.js, package.json
[TIMOB-18629] Added Node.js version check when using a Titanium SDK. Bumped node-appc version to 0.2.25.
=> [TIMOB-18629] Added Node.js version check when using a Titanium SDK.

lib/titanium.js
- Updated if condition when --colors is not passed as an argument
[Jira Ticket](https://jira.appcelerator.org/browse/TIMOB-18936)
=> [TIMOB-18936] CLI: Titanium logging does not have colors unless passing in the --colors flaf

lib/logger.js
For Windows Powershell, use cyan for debug level. Magenta and yellow don't show up.
See chalk/chalk#2 and cb1kenobi/fields#7
Also https://jira.appcelerator.org/browse/TIMOB-19126
=> Fix TIMOB-19126 Windows: Blue console output invisible in blue PowerShell window

lib/commands/sdk.js, package.json
When installing from a local zipfile, inspect the zip's manifest.json to determine if the SDK has already been installed locally. If so, do not re-install.
This is specifically a build/test performance "fix" for doing titanium_mobile testing locally. Our "scons test" command attempts to install the locally built SDK zip before running. Even if the SDK doesn't change, it will re-extract/install. titanium CLI already skips trying to reinstall when we specify a branch explicitly or implicitly and we have the SDK installed locally. This extends that behavior to installing from local zips (note that I didn't also try to do this for remote http URLs as the SDK to install, since I assume we'd need to already download it first to check). So a developer doing local unit testing shouldn't get the …
=> Avoid re-install of SDK from local zip

package-lock.json, package.json
https://jira.appcelerator.org/browse/TIMOB-26207
Revert the winston upgrade for now to fix the cli. The upgrade to 3 looks fairly involved as the `logger.cli();` functionality has been split out of winston core. Happy to do the upgrade if that's preferred though
=> [TIMOB-26207] Revert winston upgrade

Jenkinsfile
It defaults to CLI so we need to override to TIMOB
=> Fix projectKey in Jenkinsfile

lib/titanium.js, package-lock.json, package.json
This updates all the dependencies and fixes the lint error that greenkeeper has been choking on for a while now.
Closes #304, #306, #307
=> chore(deps): update dependencies

lib/commands/module.js, package-lock.json, package.json
As noted in #319 node-appc changes from iphone to ios so I've added something in to just set iphone to be super safe
=> Update node appc

lib/commands/sdk.js, package-lock.json, package.json
https://jira.appcelerator.org/browse/TIMOB-28132
=> Fix local SDK zip installs

lib/logger.js
winston 2.x reversed the meaning of the priority levels to align with RFC524, so now 0 is the
highest priority and 5 is the lowest priority. So, we need to reorder our levels so that when
winston performs a lookup against the current log level it is respected correctly
Ref - https://github.com/winstonjs/winston/blob/master/CHANGELOG.md#breaking-changes
I took a 30 minute look into moving to winston 3.x and it seems to be a good chunk of work to maintain our existing style so I decided to just make this fix first
=> fix(logger): invert log levels

lib/commands/sdk.js, package-lock.json, package.json
Fixes TIMOB-28449
Note, this PR does not add this ordering to the branch listings as it's probably a little more involved as those are not even near valid versions
=> fix(sdk): use appc.version to sort releases to ensure correct ordering

lib/logger.js, package.json
I figured it made more sense to link to titanium_mobile than this repo
=> refactor: replace jira links with titanium_mobile repo

package.json, tests/commands/test-sdk.js
This _should_ fix the CI, I've skipped the branch builds rather than remove as it might be nice to try and expose those again in future. Consequently because those tests are now skipped I had to drop the coverage requirements
=> test: skip test that require branch builds, fix org name in log

lib/commands/sdk.js
This is an attempt at handling an SDK downloaded from GitHub artifacts (i.e. from a branch or PR build) when passed as a local zip argument.
I need to fully validate if this adds too much overhead to the process for normal zips (I don't think it should as we just open and check the total files inside) and maybe see about adding some feedback to the user about what is going on.
=> feat(sdk): handle an sdk zip downloaded as an artifact from github

lib/logger.js, lib/titanium.js
Add a `--timestamp` or `ti config cli.timestamp true` flag to the CLI. It will display a timestamp (already implemented) before the log output:
```
2022-04-07T09:13:04.546Z - [INFO]  
```
=> feat(sdk): add timestamp flag

lib/commands/help.js, lib/commands/sdk.js, lib/commands/setup.js, tests/commands/test-sdk.js, tests/resources/sdks/mobilesdk/osx/9.2.0.GA/manifest.json
This PR fixes the outstanding issue where it fails processing the list of releases. It tries to destructure a regex result, but blows up if the result is null. You can't destructure null.
`ti sdk list -r` has always returned GA releases. It has never returned non-GA releases. We can possibly add a flag to list non-GA releases in the future.
Here's a list of other things I fixed:
* Fixed support for installing RC and beta release, though they do not show up when you list releases
* Removed unused variables causing lint warnings
* Updated `setup` command to use the not-so-new-anymore `new URL()` instead of the old `url.parse()`
* Disabled the `ti sdk list -b` flag as branches are not supported
* Disabled the `ti sdk list --branch <name>` option as branches are not supported
Fixes #581.
=> fix: correctly detect GA releases during sdk list and install

CHANGELOG.md, lib/commands/sdk.js, package.json
`ti sdk select` would blow up because it couldn't handle SDK directories such as `11.0.0.GA.foo`. I relaxed the regex and now it works.
Fixes #587
=> fix: Allow SDK directories to contain any version suffix

lib/commands/sdk.js, tests/commands/test-sdk.js
Will show this message after installing the SDK:
(or `ti sdk select` if you use the short form). Also added a blank before and after the line so its more visible.
I didn't want to put the SDK version in the command so you'll see the full list. Less to remember for the user and more options while running this command.
=> feat(all): add sdk select message

lib/logger.js
Will show the gradle warnings as warnings and not as errors:
=> fix: gradle warning color

src/cli.js, src/util/apply-command-config.js, src/util/tisdk.js
`--project-dir` is a global option so that the `tiapp.xml` can be loaded, however the `build` command has a `--project-dir` option and it overwrites the global one. Not only does it overwrite the option itself, it overwrites the parsed value from the global option with the default value.
=> Don't add dupe options

CHANGELOG.md, package.json, pnpm-lock.yaml, src/cli.js, test/commands/custom.test.js, test/commands/fixtures/custom/foo.js
Support for `paths.commands` was removed in the initial v7 beta, however Liveview uses this feature for `ti serve`, so alas it returns.
=> Add support for `paths.commands`

CHANGELOG.md, src/cli.js
If the Node.js version is too old, show an error and exit.
Node 16:
```
> ti
Titanium Command-Line Interface v7.0.0
Copyright TiDev, Inc. 4/7/2022-Present. All Rights Reserved.
Want to help? https://tidev.io/donate or https://tidev.io/contribute
Error: Node.js version >=18 required, current version is v16.18.1
```
=> fix: assert required node.js version, fixes #647

CHANGELOG.md, src/commands/sdk.js
When you run `ti sdk rm 12.3.0.GA`, it prompts a "yes" or "no" confirmation, however selecting either results in a falsey value and the uninstall exits.
=> fix: properly handle confirm sdk uninstall prompt response, fixes #645

CHANGELOG.md, src/util/tisdk.js
If the CLI fails to download the list of releases, print an error message.
To test, using Node 16 run `ti sdk ls -ru`.
Before:
```
Releases:
No releases found
```
After:
```
Releases:
ReferenceError: ReadableStream is not defined
```
=> fix: surface sdk install errors, fixes #648

CHANGELOG.md, src/cli.js, src/commands/config.js
Due to the way Commander.js works, if you have a command with arguments (e.g. `ti project`), Commander.js passes in `undefined` for any unset arguments.
For example, `ti project <key> <value>` would pass in `[undefined, undefined]` when running `ti project` (no key/value). The way `ti project` works is it checks the length of the args and it sees a length of 2, but the values are `undefined` causing an error.
This PR will pop `undefined` args off the args array until it hits a non-undefined value or the array is empty.
To test, simply run `ti project` with any SDK in any app using CLI v7.
=> fix: Clear undefined command args

CHANGELOG.md, package.json, src/commands/sdk.js, src/util/setup-screens.js
The part of `ti sdk install` that copies the module files was wrapped in a try/catch, but didn't surface the error.
The try/catch was basically a lazy catch when `fs.statSync(destDir).isDirectory()` throws for `destDir` not existing (e.g. new module found). Getting rid of the try/catch shows the error that `destDir` doesn't exist, which was expected, however throwing was breaking out of all the nested loops when recursively copying the module files to the dest. The solution is to remove the try/catch and use `fs.existsSync()`.
This PR also resolves 2 other related issues.
1. When installing an SDK that is already installed, it prompts the user if they want to overwrite the existing install, but it wasn't also overwriting the modules.
2. There are 3 prompts that were incorrectly handling …
=> fix: Fixed 'ti sdk install' silent fail when copying new modules to dest

CHANGELOG.md, package.json, src/cli.js
When running `ti build` without any args, it would prompt for the platform, but then it wouldn't properly load the platform config because the property was callled `iphone`, yet the prompt value for iOS was `ios` (derived from `ti.targetPlatforms` in `node-titanium-sdk`).
The second problem is the prompted platform value was not being stored back into Commander. The platform prompt happens during the first parse. When calling Commander to re-parse with the new knowledge, it would think `--platform` was not set and then overwrite the previously prompted platform with `undefined` causing platform to be prompted again.
=> fix: Rename platform config `iphone` to `ios`

CHANGELOG.md, package.json, src/cli.js
When running `ti build --platform foo`, the platform validation was being completely skipped and then the CLI would crash trying to get the platform config. As far as I can tell, this bug has been there since 7.0.0.
=> fix: Invalid --platform wasn't being validated

CHANGELOG.md, package.json, src/cli.js
With the recent "fixes" around `--platform`, the platform name `ios` and `iphone` have been normalized to `ios`, but this inadvertently broke the scan hooks since it was checking for `ios` when the directory is called `iphone`. We should rename the directory. :)
Fixes #675
=> fix: Scan ios hooks from iphone directory

src/cli.js, src/util/setup-screens.js, src/util/tisdk.js
The CLI will attempt to load the `tiapp.xml` and parse the `<sdk-version>` regardless of the command causing an error if the SDK version is not installed.
This PR fixes this behavior to only enforce the SDK not being installed for SDK commands. This means you can now run `ti config`, `ti sdk`, and `ti setup` with a `tiapp.xml` containing an unknown SDK version.
Example of reference to SDK version that is not installed:
Example of no SDKs installed:
=> fix: Improve tiapp sdk-version handling
