tidev/titanium-cli

- .npmignore
- lib/commands/lib/DashboardLogin.java
Adding the source code for connecting and logging into Appcelerator Platform.
Updated npmignore file to avoid file into the npm package.
> TIMOB-18161 Adding Java application to login into dashboard

- package.json
https://jira.appcelerator.org/browse/TIMOB-18538
> [TIMOB-18538] Update node-appc; args to spawn must be Array

- lib/commands/setup.js
https://jira.appcelerator.org/browse/TIMOB-18138
> [TIMOB-18138] CLI: ti setup, network option, setting proxy to no doesn't clear value from config file

- lib/commands/setup.js
https://jira.appcelerator.org/browse/TIMOB-17636
> [TIMOB-17636] Create Titanium SDK folder if it doesn't exist Backport

- lib/commands/lib/proxy_detect.js
- lib/commands/setup.js
https://jira.appcelerator.org/browse/TIMOB-18162
> [TIMOB-18162] Autodetect proxy configuration within ti setup Backport

- hooks/tisdk3fixes.js
- lib/commands/info.js
- lib/commands/sdk.js
https://jira.appcelerator.org/browse/TIMOB-18351
> [TIMOB-18351] Deprecate iOS and Android modules in node-appc Backport

- hooks/tisdk3fixes.js
[Jira Ticket](https://jira.appcelerator.org/browse/CLI-548)
> [CLI-548] 'Unexpected token W' on appc setup

- lib/logger.js
https://jira.appcelerator.org/browse/TIMOB-18727
> [TIMOB-18727] Android build tool warning directs user to run "ti config"

- lib/logger.js
Backport for https://github.com/appcelerator/titanium/pull/213
[TIMOB-18727](https://jira.appcelerator.org/browse/TIMOB-18727)
> [TIMOB-18727] direct warnings to stderr

- lib/commands/setup.js
- locales/en.js
Obviously ground-breaking, incredibly important stuff (I won't be accepting any Nobel Prizes due to being so ridiculously modest).
> Typo (Titainum -> Titanium)

- lib/titanium.js
- Patched _--color_ not being respected
> Patched --color argument

- hooks/tisdk3fixes.js
- lib/commands/sdk.js
https://jira.appcelerator.org/browse/TIMOB-18351
> [TIMOB-18351] Deprecate iOS and Android modules in node-appc

- lib/commands/sdk.js
- locales/en.js
https://jira.appcelerator.org/browse/CLI-860
> [CLI-860] Confusing: Did not find a release... Found release

- forge-tools/test-cov/index.js
- lib/commands/sdk.js
- lib/commands/setup.js
- lib/config.js
- package.json
- wrench -> fs-extra
- request 2.78.0 -> 2.79.0
> Replace wrench with fs-extra, update request

- package.json
> Bump node-appc to 0.2.41

- package-lock.json
- package.json
https://jira.appcelerator.org/browse/TIMOB-25429
> [TIMOB-25429] Bump to node-appc@0.2.44 for JDK 9 detection support

- Jenkinsfile
- package-lock.json
- package.json
- Bump to 5.1.1
- Fix appc-cli job name
> Bump version and fix job name

- lib/commands/sdk.js
JIRA: https://jira.appcelerator.org/browse/TIMOB-25179
> fix(sdk): set sdk as selected even if it is installed

- package-lock.json
- package.json
> chore(deps): update semver to version 6.1.1

- package-lock.json
- package.json
> chore(deps): update husky to version 2.3.0

- lib/titanium.js
- package-lock.json
- package.json
JIRA: https://jira.appcelerator.org/browse/CLI-1369
> fix: remove longjohn

- package-lock.json
- package.json
Adds `@commitlint/cli` and `@commitlint/config-conventional` and hooks it up to husky
> add commitlint

- lib/cli.js
- lib/commands/sdk.js
- lib/titanium.js
JIRA: https://jira.axway.com/browse/TIMOB-21148
To test, run a build or install an SDK.
> refactor: removed analytics call

- lib/logger.js
> Revert "fix: gradle warning color"

- src/cli.js
- test/cli/hook.test.js
Fixed bug where the original object ref was getting lost.
> Fix hook data payload

- src/util/tisdk.js
> Distiguish nightly and local builds

- .github/workflows/test.yml
- eslint.config.js
- package.json
- pnpm-lock.yaml
- src/cli.js
- src/commands/sdk.js
- src/util/setup-screens.js
- src/util/suggest.js
- src/util/version.js
- test/mock-sdk/android/cli/commands/_build.js
- test/mock-sdk/cli/commands/build.js
- test/mock-sdk/cli/commands/clean.js
- test/mock-sdk/cli/commands/create.js
- test/mock-sdk/cli/lib/creator.js
In prep for the v7 release, I updated the dependencies and removed the `packageManager` as it's kind of a pain.
> chore: Update deps

- package.json
- pnpm-lock.yaml
- src/util/tiapp.js
- test/util/tiapp.test.js
This new release of xmldom renamed `errorHandler()` to `onError()`.
> Update eslint and xmldom
